name: Selenium CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Wait for Selenium container
        run: |
          echo "Waiting for Selenium server..."
          for i in {1..30}; do
            nc -z localhost 4444 && echo "Selenium ready!" && exit 0
            sleep 1
          done
          echo "Selenium server not responding" && exit 1

      - name: Run tests with Maven
        run: mvn test
